# Generated by Django 2.2.6 on 2019-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
